### ISSUE TITLE
Command to generate data and queries showing syntax errors

### ISSUE THREAD

**Issue by Madd-Scientist** [timescale/tsbs#116]
I installed the required directories from the cmd folder manually, and the installation showed no error. 
Directories I installed: tsbs_generate_data, tsbs_generate_queries, tsbs_load_timescaledb, tsbs_load_influx, tsbs_run_queries_timescaledb, tsbs_run_queries_influx. 

On giving the command:
<pre>&apos;/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/main.go&apos; --use-case=&quot;iot&quot; --seed=123 --scale=4000     --timestamp-start=&quot;2016-01-01T00:00:00Z&quot;     --timestamp-end=&quot;2016-01-04T00:00:00Z&quot;     --log-interval=&quot;10s&quot; --format=&quot;timescaledb&quot;     | gzip &gt; /tmp/timescaledb-data.gz
</pre>

I get the following error: 

<pre>/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/main.go: line 1: //: Is a directory
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/main.go: line 2: //: Is a directory
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/main.go: line 3: //: Is a directory
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/main.go: line 4: //: Is a directory
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/main.go: line 5: syntax error near unexpected token `(&apos;
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_data/main.go: line 5: `// ClickHouse pseudo-CSV format (the same as for TimescaleDB)&apos;</pre>

On running the command to generate queries: 

<pre>&apos;/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_queries/main.go&apos; --use-case=&quot;iot&quot; --seed=123 --scale=4000     --timestamp-start=&quot;2016-01-01T00:00:00Z&quot;     --timestamp-end=&quot;2016-01-04T00:00:01Z&quot;     --queries=1000 --query-type=&quot;breakdown-frequency&quot; --format=&quot;timescaledb&quot;     | gzip &gt; /tmp/timescaledb-queries-breakdown-frequency.gz</pre> 

I get the error: 

<pre>/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_queries/main.go: line 1: //: Is a directory
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_queries/main.go: line 2: //: Is a directory
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_queries/main.go: line 3: package: command not found
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_queries/main.go: line 5: syntax error near unexpected token `newline&apos;
/home/maddscientist/go/src/github.com/timescale/tsbs/cmd/tsbs_generate_queries/main.go: line 5: `import (&apos;
</pre>

These are the same commands as listed on the README page. 
Any help regarding this would be appreciated. 

P.S. If I don't specify the path to the command directory, I get an error saying that the command "tsbs_generate_data" is not found, even after I added the directories to my $PATH. 
This error was resolved by giving the path in the command itself.

**Comment by powersam** [comment]
[root@clickhouseclusterdbone tsbs]# pwd
/data/testdata/tsbs
[root@clickhouseclusterdbone tsbs]# ls
cmd  docs  go.mod  go.sum  internal  LICENSE  load  query  README.md  scripts
[root@clickhouseclusterdbone tsbs]# go build
go: github.com/jackc/pgx/v4@v4.1.1 requires
	github.com/jackc/pgtype@v1.0.1 requires
	github.com/jackc/pgx/v4@v4.0.0-pre1.0.20190824185557-6972a5742186 requires
	github.com/jackc/pgtype@v0.0.0-20190824184912-ab885b375b90 requires
	github.com/jackc/pgx/v4@v4.0.0-20190421002000-1b8f0016e912 requires
	github.com/jackc/puddle@v0.0.0-20190413234325-e4ced69a3a2b: invalid version: git fetch --unshallow -f https://github.com/jackc/puddle in /root/go/pkg/mod/cache/vcs/c64e1e439c1833d50f3ae3451304bb415a3c9fd61932b4dd5c008f082305a4b0: exit status 128:
	fatal: git fetch-pack: expected shallow list
[root@clickhouseclusterdbone tsbs]#

**Comment by jonatas** [comment]
I think this issue is outdated as I can see the command is a bit different in the [readme](https://github.com/timescale/tsbs#data-generation).

@Madd-Scientist feel free to reopen the issue if you get the errors with the updated instructions.
