### ISSUE TITLE
Cassandra run_queries issue: no keyspace has been specified

### ISSUE THREAD

**Issue by seybi87** [timescale/tsbs#124]
Hi guys,

I am trying to run the TSBS against a Cassandra instance (version 3.11.2).

The load phase works well and the data is inserted into Cassandra. I am using the following command:

`cat /opt/workloads/data/cassandra-data.gz | gunzip | /opt/workloads/tsbs/bin/tsbs_load_cassandra --db-name="benchmark" --workers=2 --reporting-period="10s" --batch-size=10 --hosts 192.168.0.214:9042 --replication-factor 1 --consistency ONE`

An exemplary set of queries is generated with the following command:

`/opt/workloads/tsbs/bin/tsbs_generate_queries --use-case="cpu-only" --seed=123 --scale=1000 --timestamp-start="2016-01-01T00:00:00Z" --timestamp-end="2016-01-01T02:00:01Z" --queries=1000 --query-type="single-groupby-1-1-1" --format="cassandra" | gzip > /opt/workloads/data/cassandra-queries.gz`

Yet, when running these queries with:

`cat /opt/workloads/data/cassandra-queries.gz  | gunzip | /opt/workloads/tsbs/bin/tsbs_run_queries_cassandra --workers 2  --host 192.168.0.214:9042  --aggregation-plan server`

I get the following error: `No keyspace has been specified. USE a keyspace, or explicitly specify keyspace.tablename`

I checked the Cassandra instance and the `benchmark` keyspace is created and the data is inserted.

Thanks for any help how to fix this issue!

**Comment by seybi87** [comment]
I have debugged the issue and the default value for the `keyspace`, via the ` db-name` parameter is never set because the following code snippet is missing the main.go. Yet, this code snippet is required to initialize the config struct. 

```
if err := viper.Unmarshal(&config); err != nil {
		panic(fmt.Errorf("unable to decode config: %s", err))
}
```

**Comment by RobAtticus** [comment]
Merged, thank you!
