### ISSUE TITLE
tsbs_load_timescaledb not working 

### ISSUE THREAD

**Issue by ankit-jha** [timescale/tsbs#132]
I tried tsbs for benchmarking but it's not working. 
The scripts inside **scripts/load_timescaledb.sh** are missing parameters.
I got around it but the binary tsbs_load_timescaledb just gets stuck and doesn't report anything. My setup is running on minikube and I'm able to connect to it via psql utility. 

pqsql connection working
```bash
➜  timescaleDB psql -h 192.168.64.3 -p 30823 -U iot_asset_monitor -d astimescaledb
Password for user iot_asset_monitor:
psql (12.4, server 11.8)
Type "help" for help.

astimescaledb=# \q
```

tsbs_load_timescaledb gets stuck with no reporting
```bash
➜  tsbs git:(master) ✗ tsbs_load_timescaledb --postgres="sslmode=disable" --db-name=astimescaledb --host=192.168.64.3 --port=30823 --pass=a93304eb94caef31a17aae11d04181d5d009 --user=iot_asset_monitor --workers=2 --batch-size=10000 --reporting-period=10s --use-hypertable=true --use-jsonb-tags=false --in-table-partition-tag=true --hash-workers=false --time-partition-index=false --partitions=1 --chunk-time=8h --write-profile= --field-index-count=1 --do-create-db=true --force-text-format=false
^C
```

**Comment by ankit-jha** [comment]
I had to make changes to https://github.com/timescale/tsbs/blob/master/scripts/load_timescaledb.sh to get it start loading the data via go **tsbs_load_timescaledb** binary.

I have created a PR with my changes https://github.com/timescale/tsbs/pull/133/files.
Please review.

**Comment by jonatas** [comment]
@ankit-jha thanks for reporting it! I reviewed the PR. Would you mind addressing the changes?

**Comment by ankit-jha** [comment]
PR https://github.com/timescale/tsbs/pull/133/files merged.
