### ISSUE TITLE
tsbs_generate_data: command not found

### ISSUE THREAD

**Issue by abkenar** [timescale/tsbs#158]
I followed all the steps for installation, and did not get any error. But none of the tsbs commands works:

"tsbs_generate_data: command not found"

I tested on ubuntu 18 initialy and again tested on Ubuntu 20.4 . 

It would be appreciated if you can give me some hint. 

Thanks

**Comment by ichbill** [comment]
After installation, you need to put executables path into your $PATH. For me it is "/home/ubuntu/go/bin", so I added "export PATH=$PATH:/home/ubuntu/go/bin" to $HOME/.profile and my problem was solved. I'm using Ubuntu 20.4. Hope it's helpful for you.

**Comment by jonatas** [comment]
@abkenar would you mind confirming if the suggestion works for you? I'm closing the issue as it seems abandoned, feel free to reopen if the suggestion does not work for you.
