### ISSUE TITLE
Continuous aggregates

### ISSUE THREAD

**Issue by VassilisDrouzas** [timescale/tsbs#203]
Hello,

I just wanted to ask if there is the capability to benchmark queries by using continuous aggregates for TimescaleDB (or continuous queries, for InfluxDB).Is it supported by TSBS?

**Comment by ryanbooz** [comment]
At this time there is no functionality to create continuous aggregates as part of the benchmark suite. It's something we've discussed for some time haven't implemented.

Part of the challenge is that all "continuous" features like this are intended for longer-term continuous data ingestion. While we could show on most systems that and aggregate query does improve significantly with pre-aggregated data, the frequency at which the aggregate would be updated in real-life usage differs between each system. That would make it difficult to benchmark during the time of a test.
