### ISSUE TITLE
Unable to benchmark InfluxDB 2.x - Clarify supported versions

### ISSUE THREAD

**Issue by nbourdi** [timescale/tsbs#247]
Loading the generated data for influx using `tsbs_load` / `tsbs_load_influx` doesn't seem to work on the latest images (2.x). 

However, it works just fine on older versions (1.x).
Could you clarify if 2.x is indeed unsupported?

**Comment by lquenti** [comment]
I can confirm that it is, bc tsbs is [a fork of influxdatas initial benchmarks](https://github.com/influxdata/influxdb-comparisons) when they were in 1.x, but this repo unfortunately seems abandoned
