### ISSUE TITLE
Add ClickHouse to benchmark

### ISSUE THREAD

**Issue by jack-pappas** [timescale/tsbs#6]
[ClickHouse](https://clickhouse.yandex/) is another time-series database used for metrics storage and analysis on a large scale. For example, CloudFlare is storing ~6PiB of analytics data in a ClickHouse cluster:
https://blog.cloudflare.com/http-analytics-for-6m-requests-per-second-using-clickhouse/

ClickHouse also has a benchmarks/comparisons page showing performance with a number of different queries on a test dataset -- perhaps those can be included in your benchmark suite as well:
https://clickhouse.yandex/benchmark.html

**Comment by sunsingerus** [comment]
I am trying to implement ClickHouse benchmark functionality and have couple of questions regarding the code.
1. Can you, please, explain, what is the main idea behind writing generated data in text format that would be next parsed by loader? For example, for timescaledb, would it not be simpler, to generate ready-to-use `INSERT` data statements, which loader would just execute?
2. scripts/*.sh files are implemented with different code conventions. For example: `generate_data.sh` and `generate_queries.sh` are using 
```bash
dataDir=${dataDir:-/tmp}
```
convention, while `load_timescaledb.sh`
```bash
DATA_FILE_NAME=${DATA_FILE_NAME:-timescaledb-data.gz}
```
Which is the preferable one?

**Comment by sunsingerus** [comment]
@RobAtticus thank you for explanations.

1. Regarding intermediate CSV-like format. Point taken, it is a nice idea to implement and test different  target DB schemes out of the single test data set. Yes, I've seen that with TimescaleDB - two options available - either to keep the whole record in one JSON field, or use relational approach. This seems applicable with ClickHouse as well - tags can keept tags either in _classic_ tables (and use `JOIN`) or in _dictionaries_ [nice feature of ClickHouse](https://clickhouse.yandex/docs/en/operations/table_engines/dictionary/). 

I am still in the early research/design stage, mainly looking over the code, so more questions may come later.

2. Regarding shell scripts code conventions - that's not a problem at all, would make `load_clickhouse.sh` and was wondering, what style is the preferred one.

**Comment by sunsingerus** [comment]
Hi, I am still pushing ClickHouse test little-by-little, and it is moving. So, may be next week, we can take a look on a newcomer. Pull Request would be not a small one, may take some time to review and adopt!

**Comment by RobAtticus** [comment]
Thanks for the heads up! If you can, when you make the PR, include some extra commenting or documentation to let us know how/why its set up the way it is. I should go back and do that for the systems we have, but it would be good for outsiders like me to know about the choices in design.

And no worries about the size, it just may take a bit longer to fully review. We also have some release stuff with TimescaleDB that may limit my time looking at it.

**Comment by sunsingerus** [comment]
Hello everyone!
As to implementation details and some design choices.
>...include some extra commenting or documentation to let us know how/why its set up the way it is. 
>...it would be good for outsiders like me to know about the choices in design.

My approach to ClickHouse test implementation is rather straightforward:
1. Find the closest to ClickHouse implementation in terms of general likeliness and my experience (I have to have at least decent understanding of what's going on in test implementation of choice, which would the the base)
2. Clone and adjust/adopt this parent implementation in full stack - data and query generators, loader and query runner
3. Make the whole stack work :)

So, parent implementation has to be TimescaleDB. Reasons are:
1. Both are RDBMS and operate with `table` entities
2. Both operate with SQL dialects
3. (Subjective) I have some experience with Postgres and understand implementation details.

So, ClickHouse implementation is based on TimescaleDB. Now more details on subsystems.
First of all, current results are available in 'clickhouse' branch in my TSBS repo fork [https://github.com/sunsingerus/tsbs/tree/clickhouse
](https://github.com/sunsingerus/tsbs/tree/clickhouse)

1. Data generator. 
Very limited modifications, output for ClickHouse is absolutely the same as for TimescaleDB. Added **clickhouse** format keyword, which is a synonym for **timescaledb** actually.
Looks like there is no need to multiply entities and to invent special data format for ClickHouse

2. Queries generator. 
Introduced `cmd/tsbs_generate_queries/databases/clickhouse/` package with SQL queries adopted for ClickHouse. Logic is ported from TimescalDB

3. Data loader.
Introduced `tsbs_load_clickhouse` command, main files of interest are: `cmd/tsbs_load_clickhouse/db_creator.go` and `cmd/tsbs_load_clickhouse/process.go`
Logic refers to TimescaleDB implementation.

4. Queries runner
Introduced `tsbs_run_queries_clickhouse` command, main file of interest `query/clickhouse.go`
Logic refers to TimescaleDB implementation.


5. Shell scripts for convenience:
`scripts/load_clickhouse.sh`
`scripts/run_queries_clickhouse.sh`

Also I've started documentation with setup and run examples, which is available as [docs/clickhouse.md](https://github.com/sunsingerus/tsbs/blob/clickhouse/docs/clickhouse.md#how-to-run-test-ubuntu-1604-lts-example)

Also, for debug purposes mostly, I've added option to read not only from `STDIO`, but from plain file as well, mind new `-file` option.

From my point of view, I am very close to "initial version implementation", however still polishing here and there. Would make PR as soon as ready!
Hope to hear some feedback :)

**Comment by sunsingerus** [comment]
Hello everyone!
As to implementation details and some design choices.
>...include some extra commenting or documentation to let us know how/why its set up the way it is. 
>...it would be good for outsiders like me to know about the choices in design.

My approach to ClickHouse test implementation is rather straightforward:
1. Find the closest to ClickHouse implementation in terms of general likeliness and my experience (I have to have at least decent understanding of what's going on in test implementation of my choice, which would the the base)
2. Clone and adjust/adopt this parent implementation in full stack - data and query generators, loader and query runner
3. Make the whole stack work :)

So, parent implementation has to be TimescaleDB. Reasons are:
1. Both are RDBMSses and operate with `table` entities
2. Both operate with SQL dialects
3. (Subjective) I have some experience with Postgres and understand implementation details.

So, ClickHouse implementation is based on TimescaleDB.
First of all, current results are available in 'clickhouse' branch in my TSBS repo fork[https://github.com/sunsingerus/tsbs/tree/clickhouse
](https://github.com/sunsingerus/tsbs/tree/clickhouse)
Now more details on subsystems.

1. Data generator. 
Very limited modifications, output for ClickHouse is absolutely the same as for TimescaleDB. Add **clickhouse** format keyword, which is a synonym for **timescaledb** actually.
Looks like there is not need to multiply entities and to invent special data format for ClickHouse

2. Queries generator. 
Introduced `cmd/tsbs_generate_queries/databases/clickhouse/` package with SQL queries adopted for ClickHouse. Logic is ported from TimescaleDB

3. Data loader.
Introduced `tsbs_load_clickhouse` command, main files of interest are: `cmd/tsbs_load_clickhouse/db_creator.go` and `cmd/tsbs_load_clickhouse/process.go`
Logic refers to TimescaleDB implementation.

4. Queries runner
Introduced `tsbs_run_queries_clickhouse` command, main file of interest `query/clickhouse.go`
Logic refers to TimescaleDB implementation.

5. Shell scripts for convenience:
`scripts/load_clickhouse.sh`
`scripts/run_queries_clickhouse.sh`

Also I've started documentation with setup and run examples, which is available as [docs/clickhouse.md](https://github.com/sunsingerus/tsbs/blob/clickhouse/docs/clickhouse.md#how-to-run-test-ubuntu-1604-lts-example)

From my point of view, I am very close to "initial version implementation", however still polishing here and there. Would make PR as soon as ready!

Hope to hear some feedback :)

**Comment by RobAtticus** [comment]
I haven't had a chance to do a deep dive but did want to follow up on something:

> Also, for debug purposes mostly, I've added option to read not only from STDIN, but from plain file as well, mind new -file option.

Is this just for the Clickhouse binaries, or did you add support for other command lines? We'd be really appreciative of this change as a separate PR if you did it for other binaries. It's on our to-do list but haven't gotten around to it. If you just did it for Clickhouse, no worries.

**Comment by RobAtticus** [comment]
You could do it similar to this:
```
# check out your feature branch
git checkout clickhouse
# create the new PR branch
git checkout -b add-file-input
# reset changes since master, so they are unstaged
git reset master
# add individual pieces back in
git add -p
```

`git add -p` presents each piece of changes that you can either add with `y` or skip with `n` and some other options (like splitting it further) so you can add some changes from a file and not others. Once you add all the parts needed for the feature you can re-commit with a new msg and create a new PR.

**Comment by sunsingerus** [comment]
Thank you for the explanations, I'll take a look `git add -p` in practice.

As to files support - as I've already started it - let me then finish files support for all tools (let's add output file support for generator as well - for unification mostly) and make it as a PR of its own. May be separate issue should be added about that.

ClickHouse part would also receive couple commits, as I am trying to make it easier to use.

**Comment by sunsingerus** [comment]
Extracted file read/write as a separate PR.
Please, [take a look](https://github.com/timescale/tsbs/pull/24)

**Comment by sunsingerus** [comment]
Pull request [added](https://github.com/timescale/tsbs/pull/26)

**Comment by RobAtticus** [comment]
Thanks to @sunsingerus effort, this has been merged in, so I will close out the issue :)
