### ISSUE TITLE
dataset files - where to download?

### ISSUE THREAD

**Issue by paulnamuag** [timescale/tsbs#67]
I wanted to try the benchmark but I cannot find where to download these files:

timescaledb-high-cpu-1-queries.gz
timescaledb-cpu-max-all-8-queries.gz
timescaledb-groupby-orderby-limit-queries.gz
timescaledb-double-groupby-1-queries.gz
timescaledb-data.gz

Maybe you can share the link where to locate these and download them.

Thank you.

**Comment by RobAtticus** [comment]
Hi @paulnamuag , those files are actually generated using `tsbs_generate_queries` and gzipping the result.

**Comment by paulnamuag** [comment]
Thanks @RobAtticus for providing that answer. I'll try that one.
