### ISSUE TITLE
Timescale load_timescaledb.sh problem 

### ISSUE THREAD

**Issue by MuhammadBor** [timescale/tsbs#79]
input has wrong header format while loading timescaledb.sh, stated as follow: 

osboxes@osboxes:~/go/src/github.com/timescale/tsbs/scripts$ sh load_timescaledb.sh                                                            load_timescaledb.sh: 5: load_timescaledb.sh: [[: not found
Bulk loading file /tmp/timescaledb-data.gz
+ pg_isready -h localhost
localhost:5432 - accepting connections
+ cat /tmp/timescaledb-data.gz
+ gunzip
+ /home/osboxes/go/bin/tsbs_load_timescaledb --db-name=benchmark --host=localhost --user=postgres --workers=6 --batch-size=10000 --reporting-period=10s --use-hypertable=true --use-jsonb-tags=false --in-table-partition-tag=true --hash-workers=false --time-partition-index=false --partitions=1 --chunk-time=8h --write-profile= --field-index-count=1 --do-create-db=true --force-text-format=false
**2019/05/24 22:08:24 input has wrong header format: EOF**

**Comment by jonatas** [comment]
Probably this issue is outdated. @MuhammadBor, can you check with the latest version?

Now you can also use `tsbs_load timescale` and it's a generic program that loads all DBs.

Feel free to reopen the issue with more details if you get the same error.
