### ISSUE TITLE
data file in invalid format

### ISSUE THREAD

**Issue by neucloudzouaodi** [timescale/tsbs#85]
tsbs_load_timescaledb -batch-size 15000 -db-name benchmark -host 1
27.0.0.1 -port 5432 -user postgres -pass 123456 -file E:/tmp/timescaledb-data2.g
z -force-text-format false

data file in invalid format; got �7(t��=j expected tags

**Comment by blagojts** [comment]
You can't feed a gzip file directly to the loaders (tsbs_load_* commands) with the --file flag. They expect it extracted. But without the --file flag tsbs_load_timescale will expect the data on STDIN. So you can execute something like this on mac and linux
`cat timescle_data.gz | gunzip | ./tsbs_load_timescaledb --user=postgres --pass=123456 ...other-flags-here` On Windows I think you'll need PowerShell for the pipes
