### ISSUE TITLE
Make bash variable naming consistent

### ISSUE THREAD

**Issue by RobAtticus** [timescale/tsbs#9]
As pointed out in issue #6, our script files do not follow the same variable conventions. `generate_*.sh`  use a camel-case format while other use all uppercase. We should standardize on all uppercase.

**Comment by sunsingerus** [comment]
Pull request is on the way, please, take a look

**Comment by RobAtticus** [comment]
Awesome, thanks! Will look later this week as we are doing release stuff for main repo

**Comment by RobAtticus** [comment]
Fixed by #10
